{
  problems {
    # 問題文として提示するのに必要なフィールド

    id
    order
    teamIsolate
    openAtBegin
    openAtEnd

    # staff only
    code
    writer
    secretText

    body {
      id
      mode
      title
      text
      perfectPoint
      candidates
      corrects
      createdAt
      updatedAt
    }

    environments {
      id
      status
      host
      user
      password
      createdAt
      updatedAt

      team {
        name
        number
      }
    }

    supplements {
      id
      text
      createdAt
    }

    # 以降は回答一覧などの、問題文以外のフィールド

    answers {
      id
      bodies
      confirming

      createdAt

      team {
        name
        number
      }

      score {
        id
        point
        solved
      }
    }

    category {
      id
      code
      title
    }

    issues {
      id
      title
      status
      createdAt

      team {
        name
        number
      }

      comments {
        text
        fromStaff
        createdAt
      }
    }

    previousProblem {
      id
      code
    }
  }
}
