---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-db
  namespace: default
provisioner: kubernetes.io/gce-pd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "storage-db"
  hostPath:
    path: "/mnt/data"
  # nfs:
  #   server: 172.16.30.101
  #   path: "/export/default-postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: default
spec:
  storageClassName: "storage-db"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: default
spec:
  serviceName: "db"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      # priorityClassName: system-cluster-critical
      containers:
        - name: db
          image: postgres:11.3-alpine
          securityContext:
            runAsUser: 0
          args:
            - -c
            - max_connections=200
            - -c
            - shared_buffers=256MB
            - -c
            - work_mem=4MB
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-env
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  namespace: default
data:
  TZ: "Asia/Tokyo"
  POSTGRES_HOST: "db"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_MAX_CONNECTIONS: "200"
  POSTGRES_SHARED_BUFFERS: "256MB"
  POSTGRES_WORK_MEM: "4MB"
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 5432
