apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    ictsc2018-score: plasma
  name: plasma
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ictsc2018-score: plasma
    spec:
      containers:
        - image: openfresh/plasma:0.2.2
          name: plasma
          envFrom:
            - configMapRef:
                name: plasma-env
          ports:
            - name: plasma
              containerPort: 8080
      # restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plasma-env
data:
  PLASMA_DEBUG: "true"
  PLASMA_SUBSCRIBER_TYPE: "redis"
  PLASMA_SUBSCRIBER_REDIS_ADDR: "redis:6379"
  PLASMA_SUBSCRIBER_REDIS_CHANNELS: "realtime_notification"
  PLASMA_SUBSCRIBER_REDIS_OVER_MAX_RETRY_BEHAVIOR: "alive"
  PLASMA_SUBSCRIBER_REDIS_MAX_RETRY: "5"
  PLASMA_SUBSCRIBER_REDIS_TIMEOUT: "1s"
  PLASMA_SUBSCRIBER_REDIS_RETRY_INTERBAL: "5s"
  PLASMA_ORIGIN: "*"
  TZ: "Asia/Tokyo"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ictsc2018-score: plasma
  name: plasma
spec:
  ports:
    - name: "plasma"
      port: 3003
      targetPort: 8080
  clusterIP: None
  selector:
    ictsc2018-score: plasma
