# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'colorize'

gem 'graphql'
gem 'graphql-batch', require: 'graphql/batch'

gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'redis-objects'
# redis session store
gem 'redis-rails'

# gem 'sidekiq'
# gem 'sinatra', require: false

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Bulk insert.  In Rails6 is don't need it
gem 'activerecord-import'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

gem 'tzinfo-data'

group :development, :test do
  gem 'bullet' # N+1 problem
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
  # 参考程度に使う
  gem 'rails_best_practices', require: false

  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-stack_explorer'

  gem 'faker'
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'spring-commands-rspec'
  gem 'json_matchers'
  gem 'simplecov', require: false
end
