---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-db
  namespace: __VAR__NAMESPACE
provisioner: kubernetes.io/gce-pd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
  namespace: __VAR__NAMESPACE
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "storage-db"
  hostPath:
    path: "/mnt/data"
  # nfs:
  #   server: 172.16.30.101
  #   path: "/export/default-postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: __VAR__NAMESPACE
spec:
  storageClassName: "storage-db"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: __VAR__NAMESPACE
spec:
  serviceName: "db"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      # priorityClassName: system-cluster-critical
      containers:
        - name: db
          image: postgres:11.3-alpine
          securityContext:
            runAsUser: 0
          args:
            - -c
            - max_connections=200
            - -c
            - shared_buffers=256MB
            - -c
            - work_mem=4MB
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-env
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  namespace: __VAR__NAMESPACE
data:
  TZ: __VAR__TZ
  POSTGRES_HOST: __VAR__POSTGRES_HOST
  POSTGRES_USER: __VAR__POSTGRES_USER
  POSTGRES_PASSWORD: __VAR__POSTGRES_PASSWORD
  POSTGRES_MAX_CONNECTIONS: __VAR__POSTGRES_MAX_CONNECTIONS
  POSTGRES_SHARED_BUFFERS: __VAR__POSTGRES_SHARED_BUFFERS
  POSTGRES_WORK_MEM: __VAR__POSTGRES_WORK_MEM
---
apiVersion: v1
kind: Service
metadata:
  namespace: __VAR__NAMESPACE
  name: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: api-production-bind-svc
spec:
  type: ExternalName
  externalName: api.production.svc.cluster.local
