source 'https://rubygems.org'

# require to load activesupport before sinatra
gem 'activesupport',    require: ['active_support', 'active_support/core_ext']
gem 'sinatra',          require: 'sinatra/base'
gem 'rack-contrib',     require: 'rack/contrib'
gem 'rack-protection',  require: 'rack/protection'
gem 'redis-rack',       require: 'rack/session/redis'
gem 'rack-ltsv_logger'

gem 'redis'
gem 'mysql2'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'

gem 'rake'
gem 'seed-fu'
gem 'dotenv'
gem 'factory_bot'
gem 'puma', require: false
gem 'oj'
gem 'oj_mimic_json'
gem 'tzinfo-data'

group :development, :test do
  gem 'database_cleaner'
  gem 'simplecov'

  gem 'rubocop'
  gem 'rubocop-rspec'

  gem 'rack-test'
  gem 'rspec'
  gem 'rspec_junit_formatter'
end

group :development do
  gem 'racksh', require: false
  gem 'rack-lineprof'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
end
