# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'rails', '~> 6.0.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '< 6'
gem 'colorize'
gem 'oj'

gem 'graphql'
gem 'graphql-batch', require: 'graphql/batch'

gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'redis-objects'
# redis session store
gem 'redis-rails'

# gem 'sidekiq'
# gem 'sinatra', require: false

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Bulk insert.  In Rails6 is don't need it
gem 'activerecord-import'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem 'tzinfo-data'

gem 'slack-notifier'
gem 'bugsnag'

# プロダクションに必須ではないがあると便利
gem 'factory_bot_rails'
gem 'faker'

group :development, :test do
  gem 'bullet' # N+1 problem
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'database_cleaner-active_record', require: 'database_cleaner/active_record'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'json_matchers'
  gem 'shoulda-matchers'
  gem 'spring-commands-rspec'
  gem 'simplecov', require: false
end
