# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'graphql/rake_task'

Rails.application.load_tasks

# Add graphql:schema:dump
GraphQL::RakeTask::DEFAULT_OPTIONS.update(idl_outfile: 'tmp/schema.graphql', json_outfile: 'tmp/schema.json')
GraphQL::RakeTask.new(schema_name: 'ApiSchema')

namespace :db do
  # 1つのPR内のマイグレーションファイルを1ファイルにまとめたときなどに使う
  if Rails.env.development?
    task remigrate: :environment do
      Rake::Task['db:drop'].invoke
      Rake::Task['db:create'].invoke
      Rake::Task['db:migrate'].invoke
    end
  end
end
